[alias]
esp32   = "build --release --features=esp32   --target=xtensa-esp32-none-elf"
esp32c2 = "build --release --features=esp32c2 --target=riscv32imc-unknown-none-elf"
esp32c3 = "build --release --features=esp32c3 --target=riscv32imc-unknown-none-elf"
esp32c6 = "build --release --features=esp32c6 --target=riscv32imac-unknown-none-elf"
esp32h2 = "build --release --features=esp32h2 --target=riscv32imac-unknown-none-elf"
esp32s2 = "build --release --features=esp32s2 --target=xtensa-esp32s2-none-elf"
esp32s3 = "build --release --features=esp32s3 --target=xtensa-esp32s3-none-elf"

[target.'cfg(target_arch = "riscv32")']
rustflags = [
    "-C", "link-arg=-Tlinkall.x",
    "-C", "force-frame-pointers",
]

[target.'cfg(target_arch = "xtensa")']
rustflags = [
    # GNU LD
    "-C", "link-arg=-Wl,-Tlinkall.x",
    "-C", "link-arg=-nostartfiles",

    # LLD
    # "-C", "link-arg=-Tlinkall.x",
    # "-C", "linker=rust-lld",
]

[env]
ESP_LOG="INFO"

ESP_HAL_CONFIG_PSRAM_MODE="octal"
ESP_HAL_CONFIG_PLACE_SWITCH_TABLES_IN_RAM="true"
ESP_HAL_CONFIG_PLACE_ANON_IN_RAM="true"

ESP_WIFI_CONFIG_COUNTRY_CODE="GB"
ESP_WIFI_CONFIG_TX_QUEUE_SIZE="10"
ESP_WIFI_CONFIG_STATIC_RX_BUF_NUM="24"
ESP_WIFI_CONFIG_DYNAMIC_RX_BUF_NUM="64"
ESP_WIFI_CONFIG_DYNAMIC_TX_BUF_NUM="64"
ESP_WIFI_CONFIG_RX_BA_WIN="32"
#ESP_WIFI_CONFIG_TX_BA_WIN="32"
ESP_WIFI_CONFIG_MAX_BURST_SIZE="10"
ESP_WIFI_CONFIG_TICK_RATE_HZ="500"
ESP_WIFI_CONFIG_MTU="4000"

[unstable]
build-std = ["core", "alloc"]