name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  fmt:
    name: Rustfmt Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rust-lang/setup-rust@v1
        with:
          rust-version: stable
      - name: Install Rustfmt
        run: rustup component add rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy Lint
    runs-on: ubuntu-latest
    needs: fmt
    steps:
      - uses: actions/checkout@v4
      - uses: rust-lang/setup-rust@v1
        with:
          rust-version: stable
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: clippy
    steps:
      - uses: actions/checkout@v4
      - uses: rust-lang/setup-rust@v1
        with:
          rust-version: stable
      - name: Run cargo tests
        run: cargo test --workspace --locked --verbose

  publish_dry_run:
    name: Dry-run Publish
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: rust-lang/setup-rust@v1
        with:
          rust-version: stable
      - name: Dry-run cargo publish
        run: cargo publish --workspace --dry-run